### ISSUE TITLE
How would you like to define a problem definition

### ISSUE THREAD

**Issue by dvberkel** [fifth-postulate/plan#10]
In the current prototype the problem definition is hard-coded with [the code below](https://github.com/fifth-postulate/plan/blob/master/client/src/Problem.elm).

Although this is fine for the prototype, it begs the question: *How do you want to define the problem definition?*

```elm
    problem
        (emptySlots
            |> insert Monday
                [ slot { start = time 8 30, finish = time 9 15 }
                , slot { start = time 9 30, finish = time 10 15 }
                , slot { start = time 10 30, finish = time 11 15 }
                ]
            |> insert Wednesday
                [ slot { start = time 8 30, finish = time 9 15 }
                , slot { start = time 9 30, finish = time 10 15 }
                , slot { start = time 10 30, finish = time 11 15 }
                ]
            |> insert Thursday
                [ slot { start = time 8 30, finish = time 9 15 }
                , slot { start = time 9 30, finish = time 10 15 }
                , slot { start = time 10 30, finish = time 11 15 }
                ]
        )
        [ group 37 (subject "Math") (level 3) (lessons 2)
        , group 51 (subject "Spelling") (level 5) (lessons 4)
        , group 42 (subject "Math") (level 5) (lessons 1)
        , group 51 (subject "Spelling") (level 5) (lessons 4)
        ]
        [ teacher "Alice"
            |> canTeach
                [ subject "Math"
                ]
            |> isAvailableOn
                [ Monday
                , Wednesday
                ]
        , teacher "Babs"
            |> canTeach
                [ subject "Spelling"
                ]
            |> isAvailableOn
                [ Tuesday
                , Wednesday
                , Thursday
                ]
        ]
        [ student 3435
            |> memberOf
                [ groupIdentity 37
                , group 51                ]
        , student 1729
            |> memberOf
                [ groupIdentity 42
                , groupIdentity 51
                ]
        ]
```

**Comment by dvberkel** [comment]
A few options could be

* Load from JSON
* Use the above Domain Specific 
* Have a problem definition front end

**Comment by TijlKoenderink** [comment]
I think for now my ideal would be feeding it into the system via a spreadsheet (or exported as something like CSV) for maximum flexibility. In the end it probably is going to work with two interfaces:
- An API linked to GroeiWijs which directly feeds the needed infomation
- A basic frontend which allows you to define the problem

I'll leave it to you for now whether CSV/Excel import (with high degree of demand on user to provide right input with minimum errorspecificity) or a basic frontend is easier.

**Comment by dvberkel** [comment]
For now the basic frontend will be easier. And I will go for that. I will place the CSV/Excel import on the agenda for a future time.

**Comment by dvberkel** [comment]
I have given it some more thought and upon reflection I am going to pivot my decision. 

the basic frontend is fine for testing, but it would not be practical for real-world applications. So I am now going to implement a CSV/Excel importer, as per #12
