### ISSUE TITLE
How would you like to view a candidate?

### ISSUE THREAD

**Issue by dvberkel** [fifth-postulate/plan#11]
A view on a candidate solution can have multiple perspectives. How does it look like overall, how does it look for a specific student, group or teacher?

*What perspectives would you want to see a candidate solution in?*

**Comment by TijlKoenderink** [comment]
I think I would like a primary view for the candidate which is the "whole schedule" view that is generated. In a later stage it'd be interesting to see additional statistics with a candidate how "good" it is or how many violations were needed to get it to work. 

In the following spreadsheet I've given a format (with repetitive information):
https://docs.google.com/spreadsheets/d/19bkCRMobuq2gaa5RmwCDPdiQT2EyLCV31nMaMraCAIQ/edit?usp=sharing

**Comment by dvberkel** [comment]
I will provide the "whole schedule" view first.
