### ISSUE TITLE
Do Subjects need to change?

### ISSUE THREAD

**Issue by dvberkel** [fifth-postulate/plan#2]
Currently the description for subjects taught at the School of Understanding is fixed and consists of

1. Grammar
2. Spelling
3. Math

This is [modeled](https://github.com/fifth-postulate/plan/blob/5f0236cd0590239fe881cdb6bdf7928f8a7c79c4/src/SchoolOfUnderstanding.elm#L21) as

```elm
type Subject
    = Grammar
    | Spelling
    | Math
```

**question**: are subjects ever going to change?

**Comment by TijlKoenderink** [comment]
Yes, most likely the subjects are going to change based on the implementation of the algorithm (already got questions by high schools for instance)
