### ISSUE TITLE
Are teacher available throughout the day?

### ISSUE THREAD

**Issue by dvberkel** [fifth-postulate/plan#3]
In the introduction to the problem it is stated that teachers have availability on the level of an entire day. Teachers are [modeled](https://github.com/fifth-postulate/plan/blob/ed83af5f8df2c3233028eabcfe0d45f1309080b4/src/SchoolOfUnderstanding.elm#L29) as 

```elm
type alias Teacher =
    { nickname : String
    , capabilities : List Subject
    , availabilities : List Weekday
    }
```

This states that a Teacher can be identified by a nickname, has certain capabilities and is available on certain days.

**question**: Are teachers available throughout the day? Or could there be a possibility that they are only available for one of the slots?

**Comment by TijlKoenderink** [comment]
For now it is always availability per day.
