### ISSUE TITLE
Is the closed-world assumption correct?

### ISSUE THREAD

**Issue by dvberkel** [fifth-postulate/plan#4]
In modeling [teachers]( https://github.com/fifth-postulate/plan/blob/ed83af5f8df2c3233028eabcfe0d45f1309080b4/src/SchoolOfUnderstanding.elm#L29) I took the [_closed-world assumption_](https://en.wikipedia.org/wiki/Closed-world_assumption). I.e.

> the presumption that a statement that is true is also known to be true. Therefore, conversely, **what is not currently known to be true, is false**.

(emphasis mine)

This means in the description of the problem, it is not necessary to state what a teacher can not teach, because this can be deduced from the capabilities they do have.

**question**: Is this assumption correct?

**Comment by dvberkel** [comment]
This could be related to issue #2.

**Comment by TijlKoenderink** [comment]
Yes, within this model in the definition posed we will posit which subjects the teacher is able (and sometimes willing) to teach. The system should not deviate from this. In later modelling it might be that we incorporate preferences (teacher can teach two subjects but any solution that does not have the teacher do subject 2 is preferable)
