### ISSUE TITLE
Is a Group correctly modelled?

### ISSUE THREAD

**Issue by dvberkel** [fifth-postulate/plan#5]
I documented the group that I modeled with the the following comment

> A `group` is the collective `Level` of a collection of `Student`s in a certain `Subject`

**question**: Is this correct?

I [modeled](https://github.com/fifth-postulate/plan/blob/827b6b8772e55ad6f8e868d0329888148cc9a0ea/src/SchoolOfUnderstanding.elm#L42) as such

```elm
type alias Group =
    { identity : GroupIdentity
    , subject : Subject
    , level : Level
    , lessonsNeeded : Int
    }
```

**Comment by TijlKoenderink** [comment]
Yeah, that seems right:
Pieter is lid van de "Rekenen - Niveau midden groep 4"
This group gets 5 lessons a week
