### ISSUE TITLE
How do you call when a student belongs to a collection of groups?

### ISSUE THREAD

**Issue by dvberkel** [fifth-postulate/plan#6]
For each subject a student belongs to a certain group. How is the complete assignment of a student to certain groups called? I chose to use _participation_ but I do not like it.

I rather would use a domain word.

**Comment by TijlKoenderink** [comment]
In Dutch we say he is "in een groep". Closest would be "lid of deelnemer" which would be groupmember > membership I'm guessing.

**Comment by dvberkel** [comment]
@TijlKoenderink So would this model seems natural

```elm
type alias Student =
    { identity : StudentIdentity
    , memberships : Dict Subject GroupIdentity
    }
```

**Comment by TijlKoenderink** [comment]
Yes
