### ISSUE TITLE
Slots versus Sessions

### ISSUE THREAD

**Issue by dvberkel** [fifth-postulate/plan#7]
In the description of the two terms are used possible meaning the same thing. They are **slot** and **session**.

Is there a semantic difference between the two, or are they used interchangeable?

**Comment by TijlKoenderink** [comment]
No, I think these are different. Slot, or more specifically timeslot is a moment that a session can be held, "1st session on monday from 9:30-10:00" or "3rd session on friday from 10:00-10:30".

A session is a specific group, with a specific teacher in a specific timeslot working on a level in a subject.

(apologies if I've been incongruent in my definitions)

**Comment by dvberkel** [comment]
No problem in being incongruous.

Thanks for sharpening my understanding.
